spring:
  application:
    name: api-gateway
server:
  port: 8099

zuul:
  routes:
    api-cmanager:
      path: /api-cmanager/**
      serviceId: CMANAGER-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


